### ISSUE TITLE
Poking the "Pulsate" Effect button for BlackWidow Ultimate 2013 causes traceback

### ISSUE THREAD

**Issue by emersonrp** [polychromatic/polychromatic#350] opened 2021-08-20 21:49 UTC
### Details about the problem

The page for the BlackWidow Ultimate 2013 has a single "Effect" button, "Pulsate."  Pressing it gives a traceback:

```
Traceback (most recent call last):
  File ’/usr/lib/python3.9/site-packages/polychromatic/backends/openrazer.py’, line 918, in set_device_state
    rzone.pulsate(colour_1[0], colour_1[1], colour_1[2])
AttributeError: ’RazerFX’ object has no attribute ’pulsate’

```

### Operating System / Desktop Environment / Version(s)
Manjaro / KDE
Polychromatic 0.7.0
Openrazer 3.1.0

**Comment by lah7** [comment] 2021-08-21 08:42
Duplicate of #345

**Closed by lah7** 2021-08-21 08:42 UTC
Labels: bug
