### ISSUE TITLE
Still can't configure macros

### ISSUE THREAD

**Issue by gorxk** [polychromatic/polychromatic#227] opened 2020-01-06 01:22 UTC
No macros menu as shown on many plugs
Making macros to get them even work sucks a bag of dicks
Nothing shows up on the options menu "polychromatic controller" showing what  buttons it saw, time between buttons, or that even saw or heard the the buttons in anyway, nothing to say: hey here's the macro! what key do you want it on.

**Comment by lah7** [comment] 2020-01-06 12:03
Duplicate of #228. Please open one issue at a time.

**Closed by lah7** 2020-01-06 12:03 UTC
