### ISSUE TITLE
Mouse DPI resetting on every boot

### ISSUE THREAD

**Issue by soratoyuki** [polychromatic/polychromatic#528] opened 2024-09-01 17:17 UTC
### Details about the problem

Hi everyone. Sorry, but I'm still pretty noobish with Linux. I currently have a supported Razer Naga Pro Wireless v1. I've had a persistent issue with my mouse DPI resetting to 1800 DPI after every reboot, even though that's not even one of my saved onboard presets (which are 400, 800, and 3200).

That doesn't bother me too much because it should be easy to sidestep/solve--or so I thought--except my solutions also don't seem to be working.

>polychromatic-cli --dpi 3200

should be the proper terminal command, and if I put that in terminal it does work. Here are things I've attempted, based on cobbling together information that, full disclosure, I don't entirely understand (hence the messing around with syntax):

Within Pop_OS's startup applications settings, I've tried both:

>polychromatic-cli --dpi 3200
>/usr/bin/polychromatic-cli --dpi 3200

Within /usr/share/applications/polychromatic.desktop, I've tried:

>Exec=/bin/bash -c 'polychromatic-cli --dpi 3200'
>Exec=polychromatic-cli --dpi 3200
>Exec='polychromatic-cli --dpi 3200'

I also tried to setup a cronjob with

>@reboot polychromatic-cli --dpi 3200

Obviously, none of these work, and at every reboot I'm back to 1800. 

### Application Version

0.8.6

### Qt Version

5.15.6

### Operating System

Pop!_OS 22.04

### Desktop Environment

GNOME 42.9

**Comment by soratoyuki** [comment] 2024-09-01 17:47
Sorry for the double-post. I just realized that my polling rate is also resetting to 500hz instead of 1000hz after every reboot as well. I assume that makes this related to https://github.com/polychromatic/polychromatic/issues/523 but I'm not sure how to adapt that solution to my situation.

Do I just make a file called razer.sh (or something?) and have it say:

>#!/usr/bin/python3
import openrazer.client
for device in openrazer.client.DeviceManager().devices:
    if "Naga" in device.name:
        device.poll_rate = 1000
        device.dpi = 3200

and then put razer.sh into my startup applications settings? If so, where should I save razer.sh.

Truly sorry for the dumb questions.

**Comment by lah7** [comment] 2024-09-01 19:15
The Naga Pro is known to be plagued by the _"unknown serial number"_ issue:

* https://github.com/openrazer/openrazer/issues/2122

Reading the serial might work later, but possibly not at the time of log in (when `openrazer-daemon` starts). If you have OpenRazer's persistence enabled (configurable in Polychromatic: _Tools → OpenRazer → Configure_ or edit `~/.config/openrazer/razer.conf`) then you might want to try turning it off. 

If `openrazer-daemon` doesn't get a valid serial number, it's considered a new device and the persistence feature will apply some defaults _(500 Hz, 1800 DPI?)_. Turning persistence **off** only works if your mouse is able to hold settings across reboots without the driver.

You say it's a _persistent issue_, assuming this always happens - does the device behave if you replug it in before logging in / while (re)booting?

It is an OpenRazer issue, there's nothing much we can do on Polychromatic's side. 

---

As for the `polychromatic-cli` command not working, it could be running too early. `openrazer-daemon` is supposed to spawn when any program (like Polychromatic) asks for OpenRazer, so the daemon _should_ be running at that point. It's possible the daemon hasn't registered the mouse yet - entirely possible there's a delay should the mouse's firmware is putting up a fight. There are logs here if you wanted to check timestamps/errors: `~/.local/share/openrazer/logs/razer.log`.

If disabling persistence didn't do the trick, there is Python workaround script you found will do it. Create the file called `naga_settings.py` somewhere, mark it as executable (right click → properties, usually) and then add it to your start-up applications list.

```python
#!/usr/bin/python3
import openrazer.client
import time

# Wait for devices
while len(openrazer.client.DeviceManager().devices) == 0:
    time.sleep(1)

# Apply desired settings
for device in openrazer.client.DeviceManager().devices:
    if "Naga" in device.name:
        device.poll_rate = 1000
        device.dpi = 3200
```
☝🏼  I added some logic there to wait for devices. So, the script **will** accomplish its mission.

Truly sorry a Linux newbie needs to deal with this -- the only _dumb_ thing here is certain Razer firmware 😄

**Comment by soratoyuki** [comment] 2024-09-01 20:30
The script worked! Well, for some reason device.dpi = 3200 didn't, but device.dpi = (3200,3200) did. Thank you so much!

Persistence in OpenRazer settings was already turned off, not sure if I did that previously or not. As for unplugging/replugging, I don't recall every trying that. I just keep it unplugged/wireless pretty much any time I'm using the mouse, and just charge it overnight once a week or so.

**Comment by lah7** [comment] 2024-09-02 17:56
> device.dpi = 3200 didn't, but device.dpi = (3200,3200) did.

Oops, my bad. Comment amended. I should know better having built an app using OpenRazer's Python library 😅 

> The script worked!

Glad that fixes it. Since it's not a bug in Polychromatic, I'll close the issue here. Consider subscribing to openrazer/openrazer#2122 for updates 🔔 

I suspect that after the "unknown serial number" issue is fixed, you'll be able to enable the persistence feature so `openrazer-daemon` can take care of restoring your poll rate and DPI settings without needing a script workaround. Persistence was designed to deal with this scenario - since not all Razer hardware is able to retain its settings across power cycles - but the feature is tied to the serial number.

**Closed by lah7** 2024-09-02 17:56 UTC
Labels: support, openrazer
