### ISSUE TITLE
Multiple nodes per LED wash out (creating new device graphic)

### ISSUE THREAD

**Issue by rem3-1415926** [polychromatic/polychromatic#336] opened 2021-07-01 22:48 UTC
### Details about the problem
Following this guide: https://docs.polychromatic.app/devicemaps/#preparing-the-repository, which describes that "If there are multiple nodes that represent a specific LED, place those nodes into a group and assign the attributes to the parent <g> tag." The Deathstalker chroma with only 6 (or 12, funny discussion [over here](https://github.com/polychromatic/polychromatic/issues/335)) colour zones over the whole keyboard relies heavily on this. Unfortunately, only the first sub-object in the group seems to get coloured as expected, the ones further down gradually "wash out":

![polychroma_display_bug](https://user-images.githubusercontent.com/43850766/124195721-4f627180-dacb-11eb-9faa-ca93d944ead0.png)
(Colours in the 1x12 grid are: R-R - G-G - B-B - O-O - P-P - C-C, where o, p and c stand for orange, pink and cyan)

I renamed some keys to have meaningful names, and as depicted in the screenshot above: The esc. key, topmost in its respective group, is bright red, F1, F2 and those following up continuously get weaker in saturation. The same effect is visible for all 6 cells that have keys assigned. I only did x=[0,3,5,7,9,11] on y=0 (there is only y=0 in the 1x12 grid), so everything in group x0-y0 would be expected to be red, everything in group 3 (also visible in the XML editor) should be green, and so on. 
The colour zones are defined as such:
![colour_zones](https://user-images.githubusercontent.com/43850766/124197295-7ff7da80-dace-11eb-87c2-8066770a9c7d.png)
(keys entirely in within a selection border belong to the respective zone / grid cell / group, 2 out of the 6 zones are not selected here for better visibility. They naturally consist of the keys that aren't in the selected groups here.)

Also, for some reason, when doing the first tests with an image of the blackwidow, the whole key light up and the text stayed grey, while it's the other way round here, despite the graphic being only a slightly modified copy of the blackwidow file (en_GB). Not sure if this can be classified as "bug", but definitely "unexpected" behaviour. 

(Please tell me this is fixable. I don't want to have to draw a mask for everything not-key and hide a single colour patch behind, I have made bad experiences with svg and trying to cut holes into shapes...)

### Operating System / Desktop Environment / Version(s)
- Manjaro XFCE with Linux Kernel 5.10
- polychromatic V0.6.0 (installed from AUR)
- OpenRazer Daemon + Python library 3.0.1
- D-Bus 1.12.20
- DKMS 2.8

### Affected Devices
- (deathstalker chroma)

**Comment by lah7** [comment] 2021-07-02 16:18
I was able to replicate the bug. Groups `<g>` inside a group `<g>` were not being manipulated.

As an example, I tried to group a bunch of keys under one `x-y` ID:

![Screenshot_20210702_152832](https://user-images.githubusercontent.com/13032135/124289398-2cc36d80-db4a-11eb-8c30-50bcada76460.png)

![Screenshot_20210702_152956](https://user-images.githubusercontent.com/13032135/124289551-5d0b0c00-db4a-11eb-8f0d-5efe0be6875c.png)

But flattening them out using the XML indentation/arrow buttons "fixed" it:

![Screenshot_20210702_152920](https://user-images.githubusercontent.com/13032135/124289477-482e7880-db4a-11eb-8202-1b31f5b04a00.png)

![Screenshot_20210702_153020](https://user-images.githubusercontent.com/13032135/124289617-6dbb8200-db4a-11eb-9f2d-d4cfe057cd26.png)

Except for the borders were inhibiting the "washed out" problem depending on which path is first.

Both of the issues were fixed, so:

* You can now place groups inside the `x-y` group (but not any more nested groups) - a9d287366bd467a42e859d13059e01803ffeb9a8
* Paths inside group no longer "wash out" stroke colours - 94259a046fed414c428821bc07897b8424b3e3d0

But... this introduced a regression where the Tux/meta logo disappeared. I'll look into that.

Please try updating `polychromatic-git` from the AUR and confirm if this works for your SVG?

**Comment by rem3-1415926** [comment] 2021-07-02 17:06
Wow, that was fast. 
But it seems like the latest update on the AUR still is from the 28. Dec 2020? https://aur.archlinux.org/packages/polychromatic-git/

**Comment by lah7** [comment] 2021-07-02 17:10
It doesn't matter for that package. That would be when PKGBUILD was last modified. `-git` packages always grab the source code, so reinstalling will get the latest updates.

**Comment by rem3-1415926** [comment] 2021-07-02 17:58
![image](https://user-images.githubusercontent.com/43850766/124311387-f3045e00-db6d-11eb-862d-01337ff735f4.png)
Need to fix the penguin icon and find out how to address the correct grid cell when clicking on the keys ([8,3] as seen in the image doesn't exist and thus crashes the entire polychromatic software, for example), but your updated code seems to work, Thanks a lot. 

(Might raise another issue if I don't find a way to fix the clickable cells. BTW, are the scan codes still "for future use and cannot be tested at this time", as described in your guide here: https://docs.polychromatic.app/devicemaps/#preparing-the-repository ?)

Regarding the double addressed keys: I'll try some things and get back to you in the original thread I opened for that. This here is still just a first demo setup

**Comment by lah7** [comment] 2021-07-02 18:59
The broken penguin icon was because of my recent changes. To fix, add a new attribute `nochange` with value `true` for its `<g>` and two `<path>`'s.

For the out of bounds `8,3`, check all the IDs in the Inkscape XML editor, and 🗑️ delete any stray IDs.

If clicking the regions isn't working, I've encountered that before... but I'm not sure what it was exactly. It's something to do with how the SVG is marked up. See if re-ordering the XML helps. You can also upload it here and I can take a look.

Scan codes are definitely for future use and not required right now. It's intended use case is to press a key and know where to map it's LED position on the matrix. It's a little useless for your keyboard, but at the same time, means if there's a future software-based reactive effect, it can light up one of those 12 LEDs on the keyboard when a key was pressed.

> Regarding the double addressed keys: I'll try some things and get back to you in the original thread I opened for that. This here is still just a first demo setup

It's a good start! I was wondering about the other 6 LEDs. 💡 Maybe split along the middle (a top & bottom half)?

**Comment by rem3-1415926** [comment] 2021-07-03 10:37
> The broken penguin icon was because of my recent changes. To fix, add a new attribute nochange with value true for its <g> and two <path>'s. 

Done, thanks for the tip.

> For the out of bounds 8,3, check all the IDs in the Inkscape XML editor, and wastebasket delete any stray IDs 

I did initially copy the entire set of keys to break the IDs all at once, since inkscape appends some ` - <number>` to them. It seemed to work for half of the keys, while the other half was still functional despite the new suffix... :thinking: 

Anyway, that's fixed now - halfways: I can't get the clicking on keys to work if they are grouped the way I need it to have them all addressed correctly. Here's the current draft with a mixture of different arrangements, arrow up and down are the only ones that are clickable for me (they have invalid IDs, since I ran out of valid IDs without destroying too much of the tidiness of the xml. Though for once, they just throw an error message and don't crash the entire program... (or was that part of your recent fix?))
[deathstalker_chroma_en_GB.svg (Had to rename the file ending to upload here)](https://github.com/polychromatic/polychromatic/files/6758206/deathstalker_chroma_en_GB.log)
The layout is off from shifting around items in the hierarchy, it should correct itself if everything is back in order inside the "keys" group.
As a side effect, this file also shows how the keys get completely obscured by a shape with stroke but no fill.

As far as I can tell, the clicky-thing only works when the keys are sufficiently high up in the code (and thus possibly behind other drawings) _and_ sufficiently high up in the hierarchy (which is gamebreaking, as I can't have the minimum indentation required to actually address them).

However, so far I'm not too fond of this whole zone separation anyway, as it is hard to understand and over-stylised, it doesn't depict the physical LEDs at all. Which brings me back to the 50% opacity overlay (which has its draws as well), where I can't see a meaningful solution to the clickable buttons anyway. I'm honestly a bit out of ideas how to implement the clickable keys for my "special" keyboard at all... What is your quality standard / design philosophy there? Would a "read only" image be tolerable? Or a workaround with yet another "grid" image that is interactive, either separately or as a semi-transparent overlay on the keys?

**Comment by lah7** [comment] 2021-07-03 12:34
For IDs, Polychromatic goes for an exact match for `x0-y0` (as appropriate). It's really to keep the XML neat & tidy when reviewing changes and sparing the bytes.

If you can get the program to crash (forcefully quit), please run it in the Terminal and paste the traceback. Better to show an error message then lose unsaved changes -- although this should only ever happen when developing devices/graphics. 😉 

Let's continue the discussion on the graphic in https://github.com/polychromatic/polychromatic/issues/335#issuecomment-873400893.

**Comment by rem3-1415926** [comment] 2021-07-03 13:42
> For IDs, Polychromatic goes for an exact match for x0-y0 (as appropriate). It's really to keep the XML neat & tidy when reviewing changes and sparing the bytes.

This is what I was expecting, but it appears that this doesn't work as cleanly for the click recognition as it should. I think I still have a copy of a graphic laying around somewhere to replicate it... 

If I get a reproducible crash on a cell again, I'll try to get the stacktrace, but so far it hasn't happened anymore. (mainly because I can't get any clickable cells at all atm... :roll_eyes:)

**Comment by rem3-1415926** [comment] 2021-07-03 15:15
Well well well... Here we go with the stacktrace: 

When clicking (12, 0), it crashes like this:

`libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/editor.py", line 1889, in _cb_title_changed
    callbacks[self.editor.effect_type][self.editor.current_tool](x, y)
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/editor.py", line 1628, in draw_LED_to_frame
    self.data["frames"][self.current_frame][str(x)][str(y)] = self.current_colour
KeyError: '12'
Aborted (core dumped)`

However, when clicking (1, 1), it shows this error dialog:
![image](https://user-images.githubusercontent.com/43850766/124358559-323fb700-dc21-11eb-8024-528851a788ec.png)
And this error log (printed in red):
`Failed to preview on device! Exception: 
Traceback (most recent call last):
  File ’/usr/lib/python3.9/site-packages/polychromatic/controller/editor.py’, line 1633, in draw_LED_to_frame
    self.device_object.set(int(x), int(y), rgb[0], rgb[1], rgb[2])
  File ’/usr/lib/python3.9/site-packages/polychromatic/backends/openrazer.py’, line 1381, in set
    self._rdevice.fx.advanced.matrix[y, x] = (red, green, blue)
  File ’/usr/lib/python3.9/site-packages/openrazer/client/fx.py’, line 1101, in __setitem__
    assert 0 <= key[0] < self._rows, ’Row out of bounds’
AssertionError: Row out of bounds
`
closing the error window with the x-button or clicking "ok" leads to this: 
`qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1908, resource id: 11898553, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/editor.py", line 1889, in _cb_title_changed
    callbacks[self.editor.effect_type][self.editor.current_tool](x, y)
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/editor.py", line 1628, in draw_LED_to_frame
    self.data["frames"][self.current_frame][str(x)][str(y)] = self.current_colour
KeyError: '14'
Aborted (core dumped)`

I could not reproduce the effect of not crashing after the error message yet. 
But judging from a few different tries, row out of boundaries is caught (halfways, at least), but column out of boundaries is not. (row has priority, violating both ranges is caught as row access violation)

**Comment by lah7** [comment] 2021-07-03 20:11
Thanks, I'll track the crash with this issue # and will close again when it's fixed.

**Comment by rem3-1415926** [comment] 2021-07-04 23:00
The error message itself works fine, however:
Once it has been triggered, the software seems to stay locked up in the "paint key" mode, as if the LMB was never released. This leads to painting all valid keys from just hovering above them and showing the error message again for any that don't exist. This error state can be left again by clicking any valid key to set its colour, so my first guess would be that the click release doesn't get registered when raising the exception.

**Comment by lah7** [comment] 2021-07-05 09:37
I noticed that too and tried fixing it yesterday. But, fresh day, I figured out what was the root cause and it's now fixed :+1:

**Closed** 2021-07-05 09:37 UTC
Labels: bug, device map

**Comment by rem3-1415926** [comment] 2021-07-05 20:19
Great! 

Thank you for the time and work you've put into this project, I'm really happy with it now :smile:
