### ISSUE TITLE
BlackWidow Ultimate 2013's lighting effect is supported by OpenRazer, but doesn't show on Polychromatic

### ISSUE THREAD

**Issue by YamiYukiSenpai** [polychromatic/polychromatic#283] opened 2020-09-16 03:29 UTC
### Details about the problem

Lighting effects doesn't appear on Polychromatic, but it shows up on RazerGenie.
![image](https://user-images.githubusercontent.com/13153124/93288898-f24f3680-f7aa-11ea-9467-607305b20724.png)
![image](https://user-images.githubusercontent.com/13153124/93288955-0e52d800-f7ab-11ea-8b84-9fe93ec568a4.png)
I originally reported the issue [here](https://github.com/openrazer/openrazer/issues/1207).

### Operating System / Desktop Environment
Ubuntu 20.04 with Unity desktop

### Affected Devices
BlackWidow Ultimate 2013

**Comment by lah7** [comment] 2020-09-16 15:40
It's likely a bug with **v0.3.12**, which is old and crusty, but newer developments _(v1.0.0)_ haven't superseded this version yet.

Try the [`dev-1.0.0`](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0) branch - it's an unreleased "v0.5.0" version, but it may have improved support for this device in the meantime.

For convenience, here's a packaged version to try: [polychromatic_0.5.0-UNRELEASED_all.deb.gz](https://github.com/polychromatic/polychromatic/files/5233194/polychromatic_0.5.0-UNRELEASED_all.deb.gz)

    gzip -d polychromatic_0.5.0-UNRELEASED_all.deb.gz
    sudo apt install ./polychromatic_0.5.0-UNRELEASED_all.deb

If my memory recalls, the effects may not show up in the Controller because it depends on openrazer/openrazer#1149 which hasn't been merged. However, it should show in the tray applet.

**Comment by YamiYukiSenpai** [comment] 2020-09-21 17:03
Why was the stable release stuck at 0.3.12?

**Comment by lah7** [comment] 2020-09-21 19:26
Please see https://github.com/polychromatic/polychromatic/issues/263 for the development history up to this point.

**Comment by lah7** [comment] 2021-08-13 15:04
Closing as [v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0) is now officially released.

**Closed by lah7** 2021-08-13 15:04 UTC
Labels: bug, device specific

**Comment by afzalarsalan** [comment] 2021-08-15 21:36
I can confirm that the ripple option now appears on this keyboard but the actually operation seems to be nonfunctioning. Clicking on the ripple options leads to this error message

`Traceback (most recent call last):
  File ’/usr/lib/python3.9/site-packages/polychromatic/backends/openrazer.py’, line 918, in set_device_state
    rzone.pulsate(colour_1[0], colour_1[1], colour_1[2])
AttributeError: ’RazerFX’ object has no attribute ’pulsate’`

I can also confirm that this functionality still works with RazerGenie with the latest version of Openrazer 3.1.0

**Comment by lah7** [comment] 2021-08-16 09:44
There is a bug in OpenRazer's Python library which is causing this error, see #345.
