### ISSUE TITLE
Dark Mode not matching system, top menu not working correctly

### ISSUE THREAD

**Issue by dasunsrule32** [polychromatic/polychromatic#473] opened 2023-04-21 22:53 UTC
### Details about the problem

Since upgrading to Ubuntu 23.04, Polychromatic has the following two issues:
* Theme doesn't match the system dark theme correctly. I've confirmed the same issue on two computers running the application.
* When clicking the menu along the top on File then scrolling, it no longer trails the mouse and each menu item has to be clicked independently to work.

![image](https://user-images.githubusercontent.com/649815/233745590-c08936e1-f327-47ec-8317-e7ec7089db19.png)

### Operating System / Desktop Environment / Version(s)

* Ubuntu 23.04
* Gnome 44
* Polychromatic 0.8.0
* Python: 3.11.2
* Qt: 5.15.9

**Comment by lah7** [comment] 2023-04-22 15:04
> Theme doesn't match the system dark theme correctly. I've confirmed the same issue on two computers running the application.

I just checked with an Ubuntu 23.04 Live CD, and it's working as expected.

For light themes ("Default") with a light title bar, unfortunately our Qt 5 applications haven't been able to say _"Hey, my interface is dark, use a dark title bar!"_, so that would be expected for now (#400).  _Hopefully_ Qt 6 will address this. If you're using the "Dark" Ubuntu theme, it should look like this:

![image](https://user-images.githubusercontent.com/13032135/233790257-eeb03edb-0486-40af-a9b6-c678eb5943a5.png)

Your screenshot shows different window borders. Are you using Ubuntu's default theme (Default or Dark) or do you have a custom theme?

> When clicking the menu along the top on File then scrolling, it no longer trails the mouse and each menu item has to be clicked independently to work.

Works here in the 23.04 live CD, so possibly the upgrade affected some Qt configuration, or it might be an X11/Wayland (display server) thing. In either case, it's not a bug this application can fix, but we can try to find a solution.

Which session type is present?

    env | grep SESSION_TYPE

(Note that 23.04 Live CD was using `x11`)

I found this thread, which suspects it's a problem only happening under Wayland. Testing under a new user would rule out Qt configuration in your home directory. Likewise, you could try the X11 session from the login screen.

* https://discourse.ubuntu.com/t/qt5-apps-do-not-use-gtk2-theme-in-ubuntu-23-04-beta/35047/5

**Comment by dasunsrule32** [comment] 2023-04-24 18:57
> > Theme doesn't match the system dark theme correctly. I've confirmed the same issue on two computers running the application.
> 
> I just checked with an Ubuntu 23.04 Live CD, and it's working as expected.
> 
> For light themes ("Default") with a light title bar, unfortunately our Qt 5 applications haven't been able to say _"Hey, my interface is dark, use a dark title bar!"_, so that would be expected for now (#400). _Hopefully_ Qt 6 will address this. If you're using the "Dark" Ubuntu theme, it should look like this:
> 
> ![image](https://user-images.githubusercontent.com/13032135/233790257-eeb03edb-0486-40af-a9b6-c678eb5943a5.png)
> 
> Your screenshot shows different window borders. Are you using Ubuntu's default theme (Default or Dark) or do you have a custom theme?
> 
> > When clicking the menu along the top on File then scrolling, it no longer trails the mouse and each menu item has to be clicked independently to work.
> 
> Works here in the 23.04 live CD, so possibly the upgrade affected some Qt configuration, or it might be an X11/Wayland (display server) thing. In either case, it's not a bug this application can fix, but we can try to find a solution.
> 
> Which session type is present?
> 
> ```
> env | grep SESSION_TYPE
> ```
> 
> (Note that 23.04 Live CD was using `x11`)
> 
> I found this thread, which suspects it's a problem only happening under Wayland. Testing under a new user would rule out Qt configuration in your home directory. Likewise, you could try the X11 session from the login screen.
> 
> * https://discourse.ubuntu.com/t/qt5-apps-do-not-use-gtk2-theme-in-ubuntu-23-04-beta/35047/5

Yes, it's wayland, but I ran wayland on 22.10 and it worked without issue there. I'm not sure what the correlation would be there. I will look at the link you provided when I get a chance. Thank you.

**Comment by dasunsrule32** [comment] 2023-04-25 16:59
I looked at that link and the bug thread doesn't seem to exist. I also tried another user and the controller wouldn't launch at all under the new user. When it did launch, the theme was still broken.

Is there a list of dependencies that should be installed? I just want to cover the basis for the application and make sure something didn't get uninstalled during the upgrade. Thank you.

**Comment by lah7** [comment] 2023-04-25 17:40
It looks like a Wayland/Qt integration bug specific to Ubuntu 23.04. For all I know, it could be this [`qtwayland5` bug 2008657](https://bugs.launchpad.net/ubuntu/+source/qtwayland-opensource-src/+bug/2008657). Running `polychromatic-controller` in a terminal may output warnings/errors from libraries. It's up to Ubuntu to fix this in an update, as it is appears other Qt 5 apps are affected too.

The dependencies are [listed in the docs](https://docs.polychromatic.app/dependencies/#debian/ubuntu) if you wanted to try, though I see little point if you've installed the software via PPA/apt, as these packages will be installed.

Thanks for checking a second user, since that confirms it's something at a system level or new package versions in 23.04. Just to note, the controller taking a while to appear for the new user is likely caused by OpenRazer timing out because the user may not [be part of the `plugdev` group.](https://github.com/openrazer/openrazer/wiki/Troubleshooting#4-daemon-has-your-user-been-added-to-the-plugdev-group)

So, the _workarounds_ for now could be to switch back to the old but trusty X11 session (from the login screen) **or** find the Ubuntu way of configuring the correct window theme for Qt 5 + Wayland. Arch Wiki has a useful troubleshooting tip for that: 

> #### Qt applications run on GNOME Wayland have a non-matching window decoration look, even after setting a Qt theme
>
> In order to have a matching window decoration look, you have to install qgnomeplatform-qt5, and set the following environment variable: `QT_QPA_PLATFORMTHEME='gnome'` This fix is guaranteed to work with Adwaita or Adwaita-dark.
>
> -- https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#Troubleshooting

**Closed** 2023-04-25 20:08 UTC
Labels: support, polychromatic-controller

**Comment by dasunsrule32** [comment] 2023-04-26 22:20
Yeah, so that is working for you. It's not actually scrolling for me. I have to click each menu item, rather than clicking a menu and just mouse over the other menu's to activate them. I'll see if I can grab a capture later.

Did you want a separate issue opened for that? Thank you. :)

**Comment by lah7** [comment] 2023-04-27 08:39
It would seem to be another _Qt under Wayland_ bug - this time it's not Ubuntu's fault. There's nothing the application can do to fix this so please don't open an issue here. I imagine other Qt apps (Telegram, OBS, VLC, etc) are affected.

**Comment by dasunsrule32** [comment] 2023-04-27 16:29
Ok, thank you for your help. :)
