### ISSUE TITLE
"KeyError: 250" with Razer Huntsman V2

### ISSUE THREAD

**Issue by bennybenjaman** [polychromatic/polychromatic#430] opened 2022-08-09 21:17 UTC
### Details about the problem

After a system crash polychromatic will not start and outputs this error 

Traceback (most recent call last):
  File ’/usr/lib/python3/dist-packages/polychromatic/middleman.py’, line 165, in get_device
    device = module.get_device(uid)
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 607, in get_device
    ’id’: ids[rate],
KeyError: 250

Restarting the applet and backend has no effect.

### Operating System / Desktop Environment / Version(s)

Debian Sid

### Affected Devices

Blackwidow huntsman v2

**Comment by lah7** [comment] 2022-08-09 21:48
I have a code refactor sat locally that improves the integration and by extension, has fixed this. I need to pick up where I left off to get things merged.

It's because the Huntsman V2 recently gained support for polling rates in OpenRazer 3.4.0, but the current release has polling rates hardcoded, in which this error happens as we've never seen a 250 Hz poll rate before. 

For now, you can fix this by patching the file and adding 2 new lines (as root):

    /usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py

```diff
            ids = {
                125: "poll_low",
+               250: "poll_mid",
                500: "poll_mid",
                1000: "poll_high",
                2000: "poll_hyper",
                4000: "poll_hyper_4000",
                8000: "poll_hyper_8000"
            }
            labels = {
                125: "125 Hz (~8 ms)",
+               250: "250 Hz (~4 ms)",
                500: "500 Hz (~2 ms)",
                1000: "1000 Hz (~1 ms)",
                2000: "2000 Hz (~0.5 ms)",
                4000: "4000 Hz (~0.25 ms)",
                8000: "8000 Hz (~0.125 ms)"
            }
```

Reload the apps and they should work again. I believe there is a bug in OpenRazer that can't set 250 Hz yet.

**Comment by bennybenjaman** [comment] 2022-08-09 22:04
Worked out, I appreciate the help. If anyone needs to make the edit, go to lines 583 and 592 in the above file

**Comment by Kiiro-Yakumo** [comment] 2022-09-09 10:39
If I may
> Reload the apps and they should work again. I believe there is a bug in OpenRazer that can't set 250 Hz yet.
This can be the case as one other project Razergenie has 125 Hz, 500 Hz and 1000 Hz on the list but not 250 Hz.
Maybe it's not per se a deffinitive proof but seems odd that it can't set 250 Hz either.
Quite possibly Openrazer itself needs some fix.
I can confirm that the temporal fix from lah7 worked out nicely.

**Comment by lah7** [comment] 2022-11-20 20:48
The current code that's in the `master` branch (specifically 04162d9cc005fc3b45f86adf63476bae1230fd12) has fixed the issue for the next update.

Shout out and thanks to @nightsky30 for fixing the other piece that's now in OpenRazer 3.5.0: https://github.com/openrazer/openrazer/pull/1941

**Closed by lah7** 2022-11-20 20:48 UTC
Labels: bug, device specific
