### ISSUE TITLE
Ornata v2 blinking on switch between "ripple" and custom effects

### ISSUE THREAD

**Issue by SamantazFox** [polychromatic/polychromatic#372] opened 2021-11-03 15:31 UTC
### Details about the problem

When the effect is switched from "Ripple" to a custom effect, the keyboard keeps blinking, one row after another. It's similar to looking at a CRT screen in slow motion.

How to reproduce:
1) Enable the "Ripple" effect in the devices tab
2) Got to effects
3) Press play on a custom effect
4) done

NB: The custom effect on which it hapenned is a simple one. It has 6 static colors. I have not touched any of the "frame" parameters or anything more advanced than "select a color and apply to key(s)".

Proposed fix: select the "none" effect before selecting any custom effects.

### Operating System / Desktop Environment / Version(s)

OS: ArchLinux
DE: KDE
Package version: Latest from AUR
  - OpenRazer:
    * openrazer-daemon-3.1.0-1-any.pkg.tar.zst
    * openrazer-driver-dkms-3.1.0-1-any.pkg.tar.zst
    * openrazer-meta-3.1.0-1-any.pkg.tar.zst
    * python-openrazer-3.1.0-1-any.pkg.tar.zst
  - polychromatic:
    * polychromatic-0.7.2-1-any.pkg.tar.zst

### Affected Devices

Razer Ornata v2 (AZERTY variant, if that matters)

**Comment by SamantazFox** [comment] 2021-11-03 15:57
I've tried with only one color on all keys, and that's also doing it. The effect is attached below, if required.
[polychromatic-simple-test.json.gz](https://github.com/polychromatic/polychromatic/files/7468936/polychromatic-simple-test.json.gz)

**Comment by lah7** [comment] 2021-11-03 17:50
Thanks, good catch! I can confirm this on my BlackWidow Chroma.

Will get that fixed! 🔧 As I have a refactor in progress, this won't be immediately, but I think there's a logical new bit of code  that can solve this. Setting "None" before the custom effect seems the logical thing to do.

**Comment by lah7** [comment] 2021-12-23 15:09
It occurred to me that "None" might not be the best solution, since OpenRazer would persist the "None" effect until Polychromatic is loaded again, leaving the keyboard in darkness during boot/login. On top of that, some devices might not support "None".

This might be something best fixed in OpenRazer. I'm not sure, so I've opened an issue at https://github.com/openrazer/openrazer/issues/1714 for thoughts.

**Comment by lah7** [comment] 2024-10-27 19:34
This was fixed upstream:

* openrazer/openrazer#1714
* https://github.com/openrazer/openrazer/pull/2117

**Closed by lah7** 2024-10-27 19:34 UTC
Labels: bug, openrazer
