### ISSUE TITLE
DPI keeps gettting reset on Arch updates

### ISSUE THREAD

**Issue by LiamDawe** [polychromatic/polychromatic#332] opened 2021-06-14 10:21 UTC
Hi, for a little while now it seems that Polychromatic keeps seeing the DPI for my Deathadder Chroma being reset down to 100 after upgrades.

Is there a way to figure out why, and to ensure there's an actual sane default?

**Comment by lah7** [comment] 2021-06-14 11:01
Hi, do you mean that the mouse's DPI keeps resetting after Arch updates/reboot, like a very slow cursor?

If so, this is probably an issue/bug with OpenRazer's persistence. Check this file:
```
~/.config/openrazer/persistence.conf
```

I have encountered a similar issue myself, but wasn't caused by Arch upgrades. It's like `openrazer-daemon` was not saving the DPI properly on shut down. I would try:

1. Stopping `openrazer-daemon`
2. Adjust the `dpi_x` and `dpi_y` values in  `persistence.conf` (if they are wrong)
3. Restart `openrazer-daemon` (and Polychromatic)

I believe your mouse is capable of retaining its hardware settings anyway, so an alternate solution is to turn off OpenRazer's persistence:
```
~/.config/openrazer/razer.conf

restore_persistence = False
```

In future (v1.0.0), Polychromatic will add a feature for creating presets and configuring them to apply at login, so we don't rely on OpenRazer's persistence feature - which really is there for hardware that are incapable of retaining their settings across reboots.

**Comment by LiamDawe** [comment] 2021-06-14 11:05
Yeah, so sometimes after I've run updates, the mouse is incredibly slow. I open the app and sure enough, it's been set back down to 100. It seems my setting just doesn't like to stick at times.

I don't think my version has any onboard stuff to store any settings, mine is one of their older models.

Will keep an eye on this to check back next time it happens. The persistence file has currently the correct DPI settings noted.

**Comment by lah7** [comment] 2021-06-14 11:11
`*` Not to be confused with "onboard storage", I have older models too, but they always remember their last hardware setting (effect, DPI) which is what I mean.

In any case, it doesn't seem like an Polychromatic (frontend) bug - we read the value from `openrazer-daemon` and their persistence feature is the only thing that might change the DPI setting. It might be worth turning it off if there were no issues before OpenRazer 3.0 when the feature was introduced.

**Comment by LiamDawe** [comment] 2021-06-14 11:13
> * Not to be confused with "onboard storage", I have older models too, but they always remember their last hardware setting (effect, DPI) which is what I mean.

Huh, curious, how do they do that? Couldn't find any info on my googling.

I'll turn it off now and see how we get on, will report back sometime :)

**Comment by lah7** [comment] 2021-06-14 11:36
These Razer Synapse 2-era devices predominately talked to the firmware, so setting the "wave" effect retained that across power cycles -- same for brightness, DPI and even the last framebuffer of a custom (software) effect.

Just to clarify, the firmware doesn't specifically know the effect side of things, which is where OpenRazer's software-based persistence comes in. Some of the newer Synapse 3-era devices "reset" and expect the driver to do everything, effectively making them slaves to software. Apparently one device is unable to ask the firmware for a brightness value! 😀 

["Onboard memory"](https://mysupport.razer.com/app/answers/detail/a_id/1893/~/how-to-create-mouse-profiles-on-razer-synapse-3) or "onboard profiles" is some kind of feature for certain mice so you can store multiple profiles and switch between them on the fly via hardware. I don't think OpenRazer supports this.

---
Since there's nothing for me to fix, I'll close the issue, but feel free to report back/re-open if it happens again.

**Closed by lah7** 2021-06-14 11:36 UTC
Labels: openrazer, support

**Comment by LiamDawe** [comment] 2021-07-14 12:55
Had the issue again today after running updates and rebooting, even with your idea of:

`restore_persistence = False`

**Comment by lah7** [comment] 2021-07-14 14:37
I have encountered the low DPI bug before, but it seems odd that it's still happening for you even with `restore_persistence = False`.

I had an idea of a possible culprit and created a PR at https://github.com/openrazer/openrazer/pull/1558 that _might_ fix your issue. It would be worth [patching your install with those changes](https://patch-diff.githubusercontent.com/raw/openrazer/openrazer/pull/1558.patch) and see if the problem goes away.

**Comment by lah7** [comment] 2021-07-21 09:48
Just ran into the same issue myself just now. I might have caused it by updating and using the magic <kbd>SysRq</kbd> key to hurry up shut down since some process was hanging with a 1m30s time out (happens rarely), but could be coincidence.

I added the commands above on how to apply the patch, patched and hopefully that's the last of `persistence.conf` erroneously setting the DPI to 0.
