### ISSUE TITLE
openSUSE: Controller doesn't launch, but tray applet works fine.

### ISSUE THREAD

**Issue by cobbleking** [polychromatic/polychromatic#184] opened 2018-10-07 07:37 UTC
For reference I am using OpenSuSe Tumbleweed and a Blackwidow Chroma.

Here is the output of polychromatic-controller -v:
```
(polychromatic-controller:3571): Gtk-WARNING **: 02:32:49.566: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(polychromatic-controller:3571): Gtk-WARNING **: 02:32:49.566: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(polychromatic-controller:3571): Gtk-WARNING **: 02:32:49.566: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

** (polychromatic-controller:3571): WARNING **: 02:32:49.643: Failed to load shared library 'libwebkit2gtk-4.0.so.37' referenced by the typelib: /usr/lib64/libwebkit2gtk-4.0.so.37: undefined symbol: gdk_wayland_display_get_type
/usr/lib64/python3.6/site-packages/gi/types.py:226: Warning: cannot derive '__main__+AppView' from non-derivable parent type 'void'
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 136, in <module>
    class AppView(WebKit2.WebView):
  File "/usr/lib64/python3.6/site-packages/gi/types.py", line 235, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib64/python3.6/site-packages/gi/types.py", line 214, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib64/python3.6/site-packages/gi/types.py", line 226, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType: __main__+AppView (subclass of void)
```
I checked and the shared library it said it couldn't load is installed.

**Comment by lah7** [comment] 2018-10-07 15:07
For the first few warnings, GTK deprecating stuff again :roll_eyes: I'll address them in bulk along with #183 at some point.

----
openSUSE is not looking so good at the moment. There is a known segfault with WebKit2 library which we're aware of (@z3ntu packages for this distro) but this needs to be addressed by the openSUSE people:

https://bugzilla.opensuse.org/show_bug.cgi?id=1090405

It seems the same library is failing to load for you, perhaps try reinstalling WebKit2GTK and other dependencies? The `undefined symbol: gdk_wayland_display_get_type` error sounds interesting as there could be other shared libraries that are posing problems, e.g. Wayland. Are you using X.org or Wayland as your display server?

I apologise I won't be much help. :confused:  I haven't had much luck getting the tray applet and controller to work on a new and up-to-date openSUSE Leap 15 & Tumbleweed installation. :-1:

**Comment by lah7** [comment] 2018-11-19 21:53
openSUSE is working again! :tada: Turns out segfaults were caused by a missing `python3-gobject-gdk` package, due to the way openSUSE packages this [differently to other distros](https://bugzilla.opensuse.org/show_bug.cgi?id=1090405#c9). It's been added as a dependency, so it will work now on the next update.

**Closed by lah7** 2018-11-19 21:53 UTC
Labels: library issue, support
