### ISSUE TITLE
Mouse button remapping? 

### ISSUE THREAD

**Issue by ase1590** [polychromatic/polychromatic#78] opened 2017-04-19 00:33 UTC
I currently have a Razer Deathadder Chroma, and it would be nice to be able to remap the buttons on the mouse to do something other than go forward/back on webpages. 

Is there any plans for remapping mouse buttons?

**Comment by lah7** [comment] 2017-04-19 17:44
The daemon does provide some sort of basic "macro" implementation, but AFAIK this is being rewritten as it doesn't support the mouse buttons (they're not handled in software at the minute).

Once the daemon supports this, Polychromatic will start incorporating macros/button mapping. :+1:

**Comment by furai** [comment] 2019-04-13 18:28
Hey, any movement on this? I just got DA Elite and would love to be able to rebind the DPI changing keys to something more useful. :)

**Comment by lah7** [comment] 2019-04-13 20:45
Unfortunately, key mapping on OpenRazer's side has pretty much remained the same since last time.  Polychromatic still doesn't have a way to remap mouse buttons or keys.

One of the OpenRazer maintainers is focusing efforts on an entirely user space daemon, [razer_test](https://github.com/z3ntu/razer_test), which _in theory_ should make it a lot easier to implement key remapping, but it's quite some time before that's ready.

In the meantime, a couple of months ago, another user commented about some software that can remap keys. The problem is, the program doesn't work on modern distros anymore. See #193, although this proposal was in mind for supporting keypads. For mice (and keypads), we will need some modification to the OpenRazer driver regardless so any piece of software can catch their unique keypresses.

**Comment by furai** [comment] 2019-04-14 06:51
Yeah, I've skimmed through that #193 yesterday prior to posting here. Looked at software mentioned there and 7 years of inactivity doesn't bode well (fork is pretty much dead as well) Wouldn't that solution add significant lag to input? 

Anyway, thanks for answering my question so extensively. I really appreciate your help! :)

I'll just suck it up and get used to the fact that we can't remap keys on mice, at least for foreseeable future.

**Comment by Agreeable-f** [comment] 2023-04-14 15:34
has there been any developments on supporting this from openrazer or is it possible yet?

**Comment by lah7** [comment] 2023-04-14 18:55
Seems unlikely, since majority of Razer peripherals (that are known) don't remap at a hardware level. Remapping mouse buttons would have to be handled in software, which is a pretty generic feature. OpenRazer focuses on supporting Razer-specific functionality so reinventing the wheel and carrying a heavy _(inferior)_ feature isn't something on their radar.

The project recommended to use is: https://github.com/sezanzeb/input-remapper/

I'll close this issue to confirm that Polychromatic is equally unlikely to add this _(sorry to anyone watching all these years!)._ I'd like the software to focus on lighting for now, so listening to mouse clicks and having lighting react would be more our objective then providing button remapping features.

**Closed by lah7** 2023-04-14 18:55 UTC
Labels: feature request
