### ISSUE TITLE
BlackWiddow Chroma Problem with Macro Keys and Lightning

### ISSUE THREAD

**Issue by n1ghty93** [polychromatic/polychromatic#120] opened 2017-09-01 12:06 UTC
Hey,
i've got a problem with my Black Widdow Chroma (Linux Mint 18.2).
For Example ive i lock my Screen, the Light stays out. The other problem is, after a restart all the Macro Keys are gone. I have to assign them after every restart. Its a bit anoing >.<

**Comment by lah7** [comment] 2017-09-01 18:19
Hi, these are not directly Polychromatic issues, but to address them:

> ive i lock my Screen, the Light stays out

This is the daemon causing that, there is an option in this file: `~/.config/openrazer/razer.conf`

    devices_off_on_screensaver = True

Set this to `False` and restart the daemon -- this will prevent that behaviour from happening. There were once daemon options in the Controller's preferences, but I will need to re-visit and add them back.

-----
> The other problem is, after a restart all the Macro Keys are gone. I have to assign them after every restart.

Macros in general are being re-written in the daemon. I'm not sure when that'll be finished but when it is, I'll put together an interface for assigning / managing them. For now, they are literally "on the fly".

**Comment by n1ghty93** [comment] 2017-09-04 12:46
Thanks for the answer. Then ill be waiting for the new release to hopefully dont loose the keys all the time ;)

**Comment by nightsky30** [comment] 2018-04-22 23:57
I would also appreciate the re-addition of an option to toggle devices_off_on_screensaver as the same behavior occurs when I lock my XFCE session.  Thank you for the tip to toggle manually :)

**Comment by nightsky30** [comment] 2018-05-31 00:44
@lah7 I also have seen the brightness on my BlackWidow Chroma v2 be set to and remain at 0% after my system has gone to and returned from suspend.  This does not always happen.  Most times my keyboard's brightness remains set to the proper level.  When the brightness does get set to 0% on suspend I can enter the tray applet and set brightness manually after returning.

Is that a separate issue?

**Comment by lah7** [comment] 2018-05-31 15:06
@nightsky30 That's definitely a separate issue with the driver/daemon. Only the daemon might intentionally set it to 0% if the `devices_off_on_screensaver` feature is turned on, but it's set to `false` and you say it doesn't always happen :thinking: 

The OpenRazer guys will be better knowledged to ask, since I think this newer keyboard has different firmware behaviours to the original BW Chroma.

**Comment by GrayedFox** [comment] 2018-11-26 00:01
Been trying to figure out how to just turn the brightness up to full on screen wake (could also turn it back to 0 on sleep signal, potentially) - would appreciate any feedback :) https://askubuntu.com/questions/1095978/listen-for-dbus-signal-screen-awake-gnome-ubuntu-18-04

**Comment by sidharthramesh** [comment] 2020-02-26 15:35
I have an issue with the macro keys not working after system suspend. Restarting the daemon fixes it.  I have `devices_off_on_screensaver = False`. I love the project and it's the only one that got my macros working on linux. Fixing this would be great!

**Comment by lah7** [comment] 2020-02-26 19:38
Hmm, on-the-fly macros still work for me [most of the time?] after a sleep. It could be a race condition where the daemon doesn't "catch" the device after all processes wakes up and the keyboard gets power by :penguin: . Each motherboard will be different.

Re-plugging the keyboard might re-initialise macros too.

---
I'll close this issue here as it's not a bug Polychromatic can fix, but please raise OpenRazer problems at https://github.com/openrazer/openrazer/issues

This issue's a little outdated, since progress on OpenRazer's macro rewrite had stalled long ago. It's looking like Polychromatic might go with key re-mapping alone in future (see https://github.com/polychromatic/polychromatic/issues/228#issuecomment-571114396) or wait and see if the eventual OpenRazer successor [(razer_test)](https://github.com/z3ntu/razer_test) plan to re-implement on-the-fly macros.

**Closed by lah7** 2020-02-26 19:38 UTC
Labels: openrazer, support
