### ISSUE TITLE
Basilisk v3 Settings Not Sticking On Shutdown

### ISSUE THREAD

**Issue by 0pLuS0** [polychromatic/polychromatic#419] opened 2022-05-02 23:12 UTC
### Details about the problem

I have a Blackwidow v3 Tenkeyless and a Basilisk v3, I only made three changes in Polychromatic. I changed the 1st mouse dpi to 400, and I set both of the peripherals for the Effect on Static, which then showed the default Razer Green as the color.

When I shut down my computer and then turn it back on, the mouse reverts back to cycling through the colors and won't stop until I open Polychromatic and click on Static, even though it's shown hightlighted.

If I reboot my computer the Static setting is sticking, so I don't understand why it won't stick on shutdown.

I have set in /etc/rc.d/rc.modules.local; ```/sbin/razerkbd``` to have openrazer loaded on start.

### Operating System / Desktop Environment / Version(s)

Slackware 15.0 x86_64
Openbox 3.6.1
nvidia-driver-510.60.02
MSI Optix G27CQ4
xorg-server-1.20.14
qt5-5.15.3
gtk+3-3.24.31
openrazer 3.3.0
polychromatic-0.7.3

Here's a screen shot of the settings for the mouse. 

THANKS

![polychromatic](https://user-images.githubusercontent.com/36190223/166340647-14f9fe9a-33ca-444e-ab87-f36f4bc057e6.jpg)

```P.S. After posting this issue, I see what the problem is. I'm Dual Boot, Slackware 15.0 & Windows 10. When I shut down from Windows, this is when I'm seeing the problem. Hopefully there's a way to fix this, if end-users are Dual Boot, using Razer in Windows.```

**Comment by lah7** [comment] 2022-05-03 10:01
OpenRazer's daemon has a software persistence feature which is supposed to restore settings at log on. Please check this is enabled:

    ~/.config/openrazer/razer.conf

```
[Startup]
restore_persistence = True
```

The options to re-apply are stored in `~/.config/openrazer/persistence.conf`. 

If that doesn't work, the other options that Polychromatic can do is:

* Run a `polychromatic-cli` command at log on using your desktop environment's equivalent "Start-up Applications" feature. [(For example, in Cinnamon)](https://github.com/polychromatic/polychromatic/issues/416#issuecomment-1114255404)
* Write a Python script and interface with OpenRazer's Python library directly and run that at log on.
* Hang tight for the future, as I am wanting to add a feature here to conveniently set this up via GUI. Duplicate of [#333](https://github.com/polychromatic/polychromatic/issues/333).

**Comment by 0pLuS0** [comment] 2022-05-04 22:05
Interesting, the Blackwidow v3 Tenkeyless settings stuck, but the mouse wouldn't with it ```restore_persistence = False```

I set it to True and it works...

THANKS

**Comment by lah7** [comment] 2022-05-05 20:06
It varies by hardware. OpenRazer is setting hardware effects, so the firmware (especially for older models) usually remembers settings between power cycles. Razer Synapse and some of the newer Razer devices handle everything in software, so they default to spectrum on power on and expect _something on the computer_ to do all the work.

OpenRazer introduced this persistence feature to cater to those "software only" hardware. It's also possible that when support was added, it was unknown for that model. It can be turned on via Polychromatic (Controller app) too under Tools → OpenRazer → Configure.

Since that resolves the problem, I'll close this issue and track the enhancement in #333, so users can set up how they like it without needing to enable that OpenRazer feature.

**Closed by lah7** 2022-05-05 20:06 UTC
Labels: support, openrazer

**Comment by 0pLuS0** [comment] 2022-05-05 22:12
I thought with Openrazer, using ~./.config/openrazer/razer.conf that any settings I've made would persist before I log into X?

The mouse doesn't change and go Static until I log into X, but the keyboard, only half way through the boot up of Slackware is already lit solid green, as I picked.

So I guess this is an Openrazer issue actually, then...

THANKS

**Comment by lah7** [comment] 2022-05-06 07:55
It's likely because Razer Synapse handles everything in software, so when that takes over, the hardware is back to a default spectrum upon next power cycle. The hardware effect becomes "software" rather then "static". Some firmware might be smart enough to use the last hardware effect.

The trouble is, even if you set a static effect in Windows, it's actually sending a different command, like "draw a frame with all LEDs green" **(software)** rather then "activate the static effect hardware that's green" **(hardware).** If you're just wanting the same settings on both, the solution might be to uninstall Razer Synapse on Windows (and I mean, make sure it's **fully** removed), then use OpenRazer to set the hardware effect.

Since OpenRazer daemon is a user process, it's only running as soon as you log on (on most distros). Unlike Razer Synapse which I think is a Windows  driver. If you do use Razer Synapse, you could [use the OpenRazer driver sysfs directly](https://github.com/openrazer/openrazer/wiki/Using-the-keyboard-driver) by echoing a file (as root or plugdev) during system boot up.

Equally, OpenRazer doesn't technically know what the hardware is actually doing, which is where the persistence comes in. Until Razer Synapse is removed from the equation, that particular device will reset to spectrum on next power up.

I see an issue was raised over on OpenRazer, let's continue the discussion over there: https://github.com/openrazer/openrazer/issues/1807
